services:
  - type: web
    name: off-script
    env: docker
    buildCommand: docker build -t off-script .
    startCommand: docker run -p $PORT:80 off-script
    healthCheckPath: /api/openai/healthCheck
    healthCheckTimeout: 10s
    autoDeploy: true
    envVars:
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: VITE_YOUTUBE_API_KEY
        sync: false
      - key: VITE_RECAPTCHA_SITE_KEY
        sync: false
      - key: VITE_BUMPUPS_API_KEY
        sync: false
      - key: VITE_BUMPUPS_PROXY_URL
        sync: false
      - key: VITE_OPENAI_API_KEY
        sync: false
      - key: VITE_OPENAI_ASSISTANT_URL
        sync: false

  - type: web
    name: off-script-mcp
    env: node
    buildCommand: cd mcp-server && npm install
    startCommand: cd mcp-server && node index.js
    healthCheckPath: /mcp/health
    healthCheckTimeout: 10s
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MCP_HTTP_PORT
        value: $PORT